-- AlterTable
ALTER TABLE `block` ADD COLUMN `background_image_url` TEXT NULL,
    ADD COLUMN `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    ADD COLUMN `description` TEXT NULL,
    ADD COLUMN `image_url` TEXT NULL,
    ADD COLUMN `slug` VARCHAR(191) NOT NULL DEFAULT 'todo',
    ADD COLUMN `status` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `updated_at` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3);
