import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider/theme-provider";
import { Sidebar } from "@/components/sidebar";
import Providers from "./providers";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <div className="flex min-h-screen bg-gray-100">
            <div className="w-1/5 min-h-full shadow">
              <Sidebar className="flex-shrink hidden sm:block" />
            </div>
            <div className="flex flex-col flex-1 w-4/5 min-h-screen bg-gray-200 ">
              {children}
            </div>
          </div>
          <ToastContainer />
        </Providers>
      </body>
    </html>
  );
}
